export const flightsData = [
  {
    id: 1,
    name: "IndiGo 6E 302",
    airline: "IndiGo",
    img: "https://logo.clearbit.com/goindigo.in",
    rating: 4.6,
    desc: "Non-stop economy flight with on-time performance and light snacks.",
  },
  {
    id: 2,
    name: "Air India AI 542",
    airline: "Air India",
    img: "https://logo.clearbit.com/airindia.in",
    rating: 3.4,
    desc: "Full-service flight with in-flight meal and generous baggage.",
  },
  {
    id: 3,
    name: "Vistara UK 811",
    airline: "Vistara",
    img: "https://logo.clearbit.com/airvistara.com",
    rating: 4.7,
    desc: "Premium economy and business options with superior cabin service.",
  },
  {
    id: 4,
    name: "SpiceJet SG 401",
    airline: "SpiceJet",
    img: "https://logo.clearbit.com/spicejet.com",
    rating: 4.1,
    desc: "Low-cost carrier with add-on baggage and meal options.",
  },
  {
    id: 5,
    name: "Emirates EK 503",
    airline: "Emirates",
    img: "https://logo.clearbit.com/emirates.com",
    rating: 4.9,
    desc: "International long-haul with entertainment and gourmet meals.",
  },
  {
    id: 6,
    name: "Qatar QR 571",
    airline: "Qatar Airways",
    img: "https://logo.clearbit.com/qatarairways.com",
    rating: 2.8,
    desc: "Award-winning service with comfortable seating and Wi-Fi.",
  },
  {
    id: 7,
    name: "Singapore SQ 423",
    airline: "Singapore Airlines",
    img: "https://logo.clearbit.com/singaporeair.com",
    rating: 4.9,
    desc: "Premium international flight with top-notch hospitality.",
  },
  {
    id: 8,
    name: "Lufthansa LH 763",
    airline: "Lufthansa",
    img: "https://logo.clearbit.com/lufthansa.com",
    rating: 4.5,
    desc: "Europe bound flight with comfortable economy and business cabins.",
  },
  {
    id: 9,
    name: "British Airways BA 256",
    airline: "British Airways",
    img: "https://logo.clearbit.com/britishairways.com",
    rating: 4.4,
    desc: "International carrier with entertainment and meal service.",
  },
  {
    id: 10,
    name: "Etihad EY 205",
    airline: "Etihad Airways",
    img: "https://logo.clearbit.com/etihad.com",
    rating: 3.6,
    desc: "Middle-East hub connection with modern aircraft and lounges.",
  },
  {
    id: 11,
    name: "AirAsia I5 1823",
    airline: "AirAsia",
    img: "https://logo.clearbit.com/airasia.com",
    rating: 4.0,
    desc: "Budget-friendly domestic connectivity with add-on services.",
  },
  {
    id: 12,
    name: "Akasa QP 1312",
    airline: "Akasa Air",
    img: "https://logo.clearbit.com/akasaair.com",
    rating: 1.2,
    desc: "New age Indian carrier with young fleet and value fares.",
  },
];
