export const hotelsData = [
  {
    id: 1,
    name: "Taj Palace Hotel",
    img: "https://via.placeholder.com/600x400?text=Taj+Palace+Hotel",
    rating: 4.9,
    desc: "Premium 5-star hotel with luxury rooms, pool, and fine dining experience.",
  },
  {
    id: 2,
    name: "Novotel Resorts",
    img: "https://via.placeholder.com/600x400?text=Novotel+Resorts",
    rating: 4.8,
    desc: "Modern resort-style stay with spa, kids area, and private beach access.",
  },
  {
    id: 3,
    name: "Marriott Residency",
    img: "https://via.placeholder.com/600x400?text=Marriott+Residency",
    rating: 2.7,
    desc: "Executive rooms, banquet halls, and premium dining services.",
  },
  {
    id: 4,
    name: "Radisson Blu",
    img: "https://via.placeholder.com/600x400?text=Radisson+Blu",
    rating: 4.6,
    desc: "Business-friendly hotel with bar lounge and rooftop dining.",
  },
  {
    id: 5,
    name: "ITC Grand Chola",
    img: "https://via.placeholder.com/600x400?text=ITC+Grand+Chola",
    rating: 3.9,
    desc: "Luxury five-star experience with grand restaurants & spa services.",
  },
  {
    id: 6,
    name: "Hyatt Regency",
    img: "https://via.placeholder.com/600x400?text=Hyatt+Regency",
    rating: 4.5,
    desc: "Premium family stay with conference rooms and pool facilities.",
  },
  {
    id: 7,
    name: "Le Meridien",
    img: "https://via.placeholder.com/600x400?text=Le+Meridien",
    rating: 4.5,
    desc: "Stylish rooms, elegant ambience, and exclusive dining options.",
  },
  {
    id: 8,
    name: "Holiday Inn",
    img: "https://via.placeholder.com/600x400?text=Holiday+Inn",
    rating: 4.4,
    desc: "Affordable premium stay near major business locations.",
  },
  {
    id: 9,
    name: "Park Hyatt",
    img: "https://via.placeholder.com/600x400?text=Park+Hyatt",
    rating: 4.8,
    desc: "Elite luxury experience with artistic interiors and indoor spa.",
  },
  {
    id: 10,
    name: "The Oberoi",
    img: "https://via.placeholder.com/600x400?text=The+Oberoi",
    rating: 3.9,
    desc: "Classy hotel chain offering premium business class suites.",
  },
  {
    id: 11,
    name: "The Residency Towers",
    img: "https://via.placeholder.com/600x400?text=Residency+Towers",
    rating: 4.6,
    desc: "High comfort rooms with rooftop restaurants and fitness center.",
  },
  {
    id: 12,
    name: "Courtyard by Marriott",
    img: "https://via.placeholder.com/600x400?text=Courtyard+by+Marriott",
    rating: 4.7,
    desc: "Modern hotel providing global cuisines & luxurious amenities.",
  },
];
